### ISSUE TITLE
Gulp is causing layout breaks and issues with responisve hamburger nav

### ISSUE THREAD

**Issue by c055** [daigofuji/jekyll-foundation-6-starter#1]

**Comment by c055** [comment]
had to downgrade in `bower_components/foundation-sites/bower.json`
and `bower.json`

to `foundation-sites": "~6.1.0`

or maybe there is another workaround .. let me know if i can be of assistance ..

**Comment by daigofuji** [comment]
Thanks for reporting, I will look into it. If you do figure it out the cause, please let me know.

**Comment by daigofuji** [comment]
You may have to run `npm update`

**Comment by daigofuji** [comment]
Actually I see what you mean. It is happening to me now. Investigating.

**Comment by daigofuji** [comment]
As of 1c6530d69076c75387922c61ed3c5f56172298c6, this issue is fixed. Sorry it took three+ month. 🙇
