### ISSUE TITLE
Double vertical scrollbar in Chrome

### ISSUE THREAD

**Issue by ChuckMac** [daigofuji/jekyll-foundation-6-starter#2]
In Chrome by default you end up with an extra vertical scrollbar.  You can see this on the demo site:

![image](https://cloud.githubusercontent.com/assets/1966834/23461597/9117ebd6-fe58-11e6-81f8-d9a566422efa.png)

I was able to address by setting this in my custom scss:

`
.off-canvas-wrapper {
	overflow-x: inherit;
}
`

**Comment by daigofuji** [comment]
Thanks. Glad you were able to address it.
