### ISSUE TITLE
Cannot find module 'gulp-load-plugins'

### ISSUE THREAD

**Issue by AnaghSharma** [daigofuji/jekyll-foundation-6-starter#3]
<img width="741" alt="screen shot 2017-07-26 at 11 16 46 pm" src="https://user-images.githubusercontent.com/6823117/28635582-c121c292-7258-11e7-991e-15ad15259838.png">

I am getting this error whenever I run `npm start`. I had been referencing another project for "Jekyll
with Foundation" but it was not working with Github Pages. So I deleted all the contents from local and remote.After that I copied the content of this repo to my [username].github.io repo and tried testing it locally and eventually got this error. Since I am new to Front end and Jekyll, I could not figure out what went wrong. 

Any help would be appreciated.

Thanks.

**Comment by Fitzonreee** [comment]
Did you run npm install?

**Comment by AnaghSharma** [comment]
@Fitzonreee Yes. I did.

Edit: Restarted mac. Ran `npm install` again. This time did not get any error in `npm start`. Ran `bundle install` which threw a couple of errors (json not getting installed, nokogiri not getting installed and what not). Updated xcode command line tools. This time no error.

One thing I would like to ask is - to test locally do I have to run `bundle install` and `bundle exec jekyll serve --watch` only or do I also have to run `npm start` everytime with it.

Thanks.

**Comment by daigofuji** [comment]
Hi `npm start` will compile css from scss. If you are not editing scss then you don't have to run it. I agree that the documentation is confusing, I am updating it to clarify a bit. Thanks.

**Comment by AnaghSharma** [comment]
Thanks a lot. I figured that out by myself (by hit and trial).  :)

Also while installing all the tools, I got a `npm WARN` saying we recommend `yarn` and `webpack` for new projects (instead of bower). So would you recommend to migrate to `yarn` or stick to `bower`?

<img width="1678" alt="screen shot 2017-07-26 at 10 38 22 pm" src="https://user-images.githubusercontent.com/6823117/29002653-d4ad0d66-7ac4-11e7-9ba5-1fa114db565b.png">
